# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'movieTinder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for movieTinder
  pod 'RealmSwift'

  target 'movieTinderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'movieTinderUITests' do
    # Pods for testing
  end

end
