# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'movieTinder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for movieTinder
  pod 'RealmSwift'

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'

  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # or pod ‘Firebase/AnalyticsWithoutAdIdSupport’
  # for Analytics without IDFA collection capability

# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  target 'movieTinderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'movieTinderUITests' do
    # Pods for testing
  end

end
